# Generated by Django 6.0.3 on 2026-03-17 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional company data')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='crm_company_name_895a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('phone', 'Phone Call'), ('email', 'Email'), ('referral', 'Referral'), ('social', 'Social Media'), ('other', 'Other')], default='other', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing contacts (list of strings, max 50)')),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contact data')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('meeting', 'Meeting'), ('note', 'Note')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name', 'first_name'], name='crm_contact_last_na_cda0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='crm_contact_phone_189db8_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact', '-occurred_at'], name='crm_interac_contact_f766b7_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_type'], name='crm_interac_interac_8c4671_idx'),
        ),
    ]
