# Generated by Django 6.0.3 on 2026-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_plane_url', models.URLField(help_text="Tyler's inbound webhook URL, e.g. https://guildhouse.example.com/api/v1/capstone/inbound/")),
                ('shared_secret', models.CharField(help_text="Shared secret for HMAC signature verification. Must match Tyler's config.", max_length=255)),
                ('instance_id', models.CharField(help_text="This instance's unique ID, e.g. 'entropyopposition'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Configuration',
            },
        ),
    ]
